import { defineConfig } from "oxlint";

export default defineConfig({
  ignorePatterns: [
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".omp/**",
    ".specify/**",
    "tools/oxlint/anti-slop/**",
  ],
  plugins: ["eslint", "import", "node", "oxc", "promise", "typescript", "unicorn", "vitest", "vue"],
  // jsPlugins: [{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" }],
  rules: {
    // "anti-slop/no-chained-type-assertions": "error",
    // "anti-slop/no-conditional-empty-object-spread": "error",
    // "anti-slop/no-known-value-widening": "error",
    // "anti-slop/no-module-mocking": "error",
    // "anti-slop/no-object-parameters": "error",
    // "anti-slop/no-reflect-apply": "error",
    // "anti-slop/no-reflect-get": "error",
    // "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
    // "anti-slop/no-shape-in-symbol-names": "error",
    // "anti-slop/no-unknown-parameters": "error",
    // "anti-slop/no-unknown-returns": "error",
    // "anti-slop/no-unknown-type-aliases": "error",
    // "anti-slop/no-unsafe-dictionary-type": "error",
    // "anti-slop/no-widen-then-assert": "error",
    // "anti-slop/require-safety-comment-for-type-assertion": "error",
    "constructor-super": "error",
    "default-case": "error",
    "no-inner-declarations": "error",
    "typescript/array-type": ["error", { default: "array-simple" }],
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/import-style": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/prefer-export-from": "error",
  },
});
